{
 "title": "Glen Dimplex Heat Pump",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Outside temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_outside_temperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hot water temp",
   "type": "stat",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_hot_water_temperature",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hot water diff",
   "type": "stat",
   "description": "temp - setpoint",
   "gridPos": { "h": 6, "w": 5, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_hot_water_temperature - ignoring(domain)glendimplex_analog_hot_water_setpoint",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heating diff",
   "type": "stat",
   "description": "flow - goal",
   "gridPos": { "h": 6, "w": 5, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_flow_in_temperature - ignoring(domain)glendimplex_analog_heating_setpoint",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "glendimplex_analog_heating_goal_temperature",
     "legendFormat": "Zieltemperatur / Heating goal"
    },
    {
     "expr": "glendimplex_analog_flow_in_temperature",
     "legendFormat": "Vorlauf / Flow"
    },
    {
     "expr": "glendimplex_analog_return_temperature",
     "legendFormat": "Rücklauf / Return"
    },
    {
     "expr": "glendimplex_analog_outside_temperature",
     "legendFormat": "Außentemperatur / Outside temp"
    },
    {
     "expr": "glendimplex_analog_hot_water_temperature",
     "legendFormat": "Warmwasser / Domestic hot water"
    },
    {
     "expr": "glendimplex_analog_hot_water_setpoint",
     "legendFormat": "Warmwasser Wunschtemperatur / Hot water setpoint"
    }
   ]
  },
  {
   "title": "Pressures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "pressurebar" } },
   "targets": [
    {
     "expr": "glendimplex_analog_high_pressure_sensor_bar",
     "legendFormat": "Hochdrucksensor / High Pressure Sensor"
    },
    {
     "expr": "glendimplex_analog_low_pressure_sensor_bar",
     "legendFormat": "Niederdrucksensor / Low Pressure Sensor"
    }
   ]
  },
  {
   "title": "Betriebsstunden / Operating Hours",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 0, "y": 28 }
  },
  {
   "title": "Heat Pump / Wärmepumpe",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_heating_pump_operating_hours",
     "legendFormat": "Wärmepumpe / Heatpump"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_fan_operating_hours",
     "legendFormat": "Ventilator / Fan"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_additional_pump_operating_hours",
     "legendFormat": "Zusatzpumpe / Additional pump"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_compressor2_operating_hours",
     "legendFormat": "Compressor 2"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_compressor1_operating_hours",
     "legendFormat": "Compressor 1"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_hot_water_pump_operating_hours",
     "legendFormat": "Warmwasserpumpe / Hot water pump"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_second_heater_operating_hours",
     "legendFormat": "2. Wärmeerzeuger / 2nd heater"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "hours" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "glendimplex_analog_flange_heater_operating_hours",
     "legendFormat": "Flanschheizung / Flange heater"
    }
   ]
  }
 ]
}